/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    testimonials: Testimonial;
    faqs: Faq;
    categories: Category;
    brands: Brand;
    tags: Tag;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    seo: Seo;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'customer')[];
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL canónica en español, compartida entre idiomas (minúsculas-con-guiones).
   */
  slug: string;
  layout: (
    | HeroBlock
    | CtaBlock
    | InfoSectionBlock
    | GalleryBlock
    | TestimonialsBlock
    | FaqBlock
    | NewsletterBlock
    | FeaturedProductsBlock
    | FeaturedCategoriesBlock
    | ImpactStatsBlock
  )[];
  seo?: {
    /**
     * Overrides document title in <title> / og:title when set.
     */
    title?: string | null;
    description?: string | null;
    /**
     * Social share image (Open Graph).
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  title: string;
  subtitle?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  mediaPosition?: ('background' | 'right' | 'left' | 'none') | null;
  actions?:
    | {
        link?: {
          type?: ('custom' | 'internal') | null;
          label?: string | null;
          /**
           * Absolute URL or site path (e.g. https://… or /shop).
           */
          url?: string | null;
          /**
           * Locale-free path (e.g. /shop, /about). Storefront prefixes locale.
           */
          path?: string | null;
          newTab?: boolean | null;
          appearance?: ('primary' | 'secondary' | 'ghost' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  actions?:
    | {
        link?: {
          type?: ('custom' | 'internal') | null;
          label?: string | null;
          /**
           * Absolute URL or site path (e.g. https://… or /shop).
           */
          url?: string | null;
          /**
           * Locale-free path (e.g. /shop, /about). Storefront prefixes locale.
           */
          path?: string | null;
          newTab?: boolean | null;
          appearance?: ('primary' | 'secondary' | 'ghost' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  style?: ('brand' | 'sand' | 'outline') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoSectionBlock".
 */
export interface InfoSectionBlock {
  eyebrow?: string | null;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  media?: (number | null) | Media;
  layout?: ('textMedia' | 'mediaText' | 'centered') | null;
  link?: {
    type?: ('custom' | 'internal') | null;
    label?: string | null;
    /**
     * Absolute URL or site path (e.g. https://… or /shop).
     */
    url?: string | null;
    /**
     * Locale-free path (e.g. /shop, /about). Storefront prefixes locale.
     */
    path?: string | null;
    newTab?: boolean | null;
    appearance?: ('primary' | 'secondary' | 'ghost' | 'link') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'infoSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  title?: string | null;
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  columns?: ('2' | '3' | '4') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  eyebrow?: string | null;
  title?: string | null;
  selection?: ('manual' | 'latest') | null;
  items?: (number | Testimonial)[] | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  /**
   * Title or context (e.g. Guest · Valle de Bravo).
   */
  role?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Optional 1–5 star rating.
   */
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  eyebrow?: string | null;
  title?: string | null;
  selection?: ('manual' | 'category' | 'all') | null;
  items?: (number | Faq)[] | null;
  /**
   * Matches FAQ category field (e.g. shipping).
   */
  category?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Grouping key (e.g. shipping, products). Used by FAQ blocks.
   */
  category?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  eyebrow?: string | null;
  title: string;
  description?: string | null;
  placeholder?: string | null;
  buttonLabel?: string | null;
  successMessage?: string | null;
  /**
   * Optional external form/list id (provider-specific).
   */
  formId?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductsBlock".
 */
export interface FeaturedProductsBlock {
  eyebrow?: string | null;
  title?: string | null;
  description?: string | null;
  selection?: ('manual' | 'category') | null;
  products?: (number | Product)[] | null;
  category?: (number | null) | Category;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL estable, escrito principalmente en español y compartido entre idiomas (p. ej. cacao-de-montana).
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short copy beside the price and purchase controls. The full description appears in the accordion.
   */
  summary?: string | null;
  /**
   * System-managed date. It does not change when unpublishing or republishing.
   */
  firstPublishedAt?: string | null;
  /**
   * Drag sections to reorder. Translate title and content in each locale. Hidden or empty sections do not appear in the shop. Public information only.
   */
  informationSections?:
    | {
        /**
         * Unique identifier, e.g. care. It cannot change after saving; the title can.
         */
        key: string;
        title?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Overrides document title in <title> / og:title when set.
     */
    title?: string | null;
    description?: string | null;
    /**
     * Social share image (Open Graph).
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Primary category. It owns the storefront breadcrumb path.
   */
  category?: (number | null) | Category;
  /**
   * Optional extra browsing categories. Do not repeat the primary category.
   */
  additionalCategories?: (number | Category)[] | null;
  brand?: (number | null) | Brand;
  /**
   * Reusable public labels. Operational labels do not belong here.
   */
  taxonomyTags?: (number | Tag)[] | null;
  /**
   * Legacy free-text tags preserved for migration review. Assign reusable Public tags above.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * ISO 3166-1 alpha-2 code shared between locales, for example AR or BR.
   */
  countryOfOrigin?: string | null;
  region?: string | null;
  community?: string | null;
  /**
   * Public content. When present, it replaces the legacy Origin & impact section body to avoid duplication.
   */
  originStory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        /**
         * Optional editorial image or poster for an external video. If empty, a YouTube thumbnail is generated.
         */
        image?: (number | null) | Media;
        /**
         * Only youtube.com or youtu.be links are accepted. Do not paste iframe code.
         */
        externalVideoUrl?: string | null;
        isPrimary?: boolean | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Los productos discontinuados siguen visibles, pero no se pueden comprar.
   */
  lifecycleStatus?: ('active' | 'discontinued') | null;
  /**
   * Stock for this sellable item. Zero means sold out. For variant products, edit stock on each variant.
   */
  inventory?: number | null;
  /**
   * For sizes such as 15g / 20g. Select option types, then create and publish a sellable variant for each size. Options alone do not create stock or prices.
   */
  enableVariants?: boolean | null;
  /**
   * Reusable choices only. Save the product before creating its sellable variants below.
   */
  variantTypes?: (number | VariantType)[] | null;
  /**
   * Create one record per combination. Select its options, enable ARS, enter its price and stock, then Publish. An empty list or draft-only variants cannot be purchased.
   */
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInARSEnabled?: boolean | null;
  /**
   * Selling price of this item. For products with variants, set the price inside each sellable variant; the parent price is not used.
   */
  priceInARS?: number | null;
  /**
   * Unique, stable identifier for this sellable item. It cannot be edited after saving.
   */
  sku?: string | null;
  barcode?: string | null;
  oneOfAKind?: boolean | null;
  netContent?: number | null;
  netContentUnit?: ('g' | 'ml' | 'unit') | null;
  salesUnit?: ('unit' | 'pack') | null;
  packedWeightGrams?: number | null;
  packageLengthMm?: number | null;
  packageWidthMm?: number | null;
  packageHeightMm?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL canónica en español, compartida entre idiomas.
   */
  slug: string;
  description?: string | null;
  /**
   * Opcional. Se muestra antes que el icono.
   */
  image?: (number | null) | Media;
  /**
   * Opcional. Se usa cuando no hay imagen.
   */
  icon?: ('leaf' | 'mountain' | 'sun' | 'ritual' | 'heart') | null;
  /**
   * Optional parent used for category context and breadcrumbs.
   */
  parent?: (number | null) | Category;
  displayOrder: number;
  isVisible: boolean;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Stable identity shared between EN and ES.
   */
  slug: string;
  logo?: (number | null) | Media;
  description?: string | null;
  /**
   * Optional ISO 3166-1 alpha-2 code, for example AR.
   */
  countryCode?: string | null;
  website?: string | null;
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  label: string;
  /**
   * Stable identity shared between EN and ES.
   */
  slug: string;
  description?: string | null;
  group?: string | null;
  isVisible: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable option types, such as size or color. Translate labels without changing the shared code.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  /**
   * Choose one value per option type. Define the selling price separately below.
   */
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Reusable labels such as 15g and 20g. These are not sellable variants and have no prices or stock.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * Stable identifier, e.g. 20g. Never enter a selling price here. Set prices on sellable variants.
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Each record is a purchasable combination with its own ARS price and stock. Save and publish every variant, not only the parent product.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  /**
   * Choose one value per option type. Define the selling price separately below.
   */
  options: (number | VariantOption)[];
  /**
   * Stock for this sellable item. Zero means sold out. For variant products, edit stock on each variant.
   */
  inventory?: number | null;
  priceInARSEnabled?: boolean | null;
  /**
   * Selling price of this item. For products with variants, set the price inside each sellable variant; the parent price is not used.
   */
  priceInARS?: number | null;
  /**
   * Unique, stable identifier for this sellable item. It cannot be edited after saving.
   */
  sku?: string | null;
  barcode?: string | null;
  oneOfAKind?: boolean | null;
  netContent?: number | null;
  netContentUnit?: ('g' | 'ml' | 'unit') | null;
  salesUnit?: ('unit' | 'pack') | null;
  packedWeightGrams?: number | null;
  packageLengthMm?: number | null;
  packageWidthMm?: number | null;
  packageHeightMm?: number | null;
  lifecycleStatus?: ('active' | 'discontinued') | null;
  image?: (number | null) | Media;
  combinationKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCategoriesBlock".
 */
export interface FeaturedCategoriesBlock {
  eyebrow?: string | null;
  title?: string | null;
  description?: string | null;
  selection?: ('manual' | 'latest') | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCategories';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImpactStatsBlock".
 */
export interface ImpactStatsBlock {
  eyebrow?: string | null;
  title?: string | null;
  stats: {
    /**
     * Display value (e.g. 120+, 3k).
     */
    value: string;
    label: string;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'impactStats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL canónica en español, compartida entre idiomas (minúsculas-con-guiones).
   */
  slug: string;
  /**
   * Short summary for cards and listings.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  seo?: {
    /**
     * Overrides document title in <title> / og:title when set.
     */
    title?: string | null;
    description?: string | null;
    /**
     * Social share image (Open Graph).
     */
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  acceptCurrentPrices?: boolean | null;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        amount?: number | null;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'ARS' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | User;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'ARS' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | User;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'ARS' | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        infoSection?: T | InfoSectionBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        featuredProducts?: T | FeaturedProductsBlockSelect<T>;
        featuredCategories?: T | FeaturedCategoriesBlockSelect<T>;
        impactStats?: T | ImpactStatsBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  body?: T;
  media?: T;
  mediaPosition?: T;
  actions?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              url?: T;
              path?: T;
              newTab?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  actions?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              url?: T;
              path?: T;
              newTab?: T;
              appearance?: T;
            };
        id?: T;
      };
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfoSectionBlock_select".
 */
export interface InfoSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  body?: T;
  media?: T;
  layout?: T;
  link?:
    | T
    | {
        type?: T;
        label?: T;
        url?: T;
        path?: T;
        newTab?: T;
        appearance?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  title?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  columns?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  selection?: T;
  items?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  selection?: T;
  items?: T;
  category?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  placeholder?: T;
  buttonLabel?: T;
  successMessage?: T;
  formId?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductsBlock_select".
 */
export interface FeaturedProductsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  selection?: T;
  products?: T;
  category?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCategoriesBlock_select".
 */
export interface FeaturedCategoriesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  selection?: T;
  categories?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImpactStatsBlock_select".
 */
export interface ImpactStatsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  publishedAt?: T;
  authors?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  avatar?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  icon?: T;
  parent?: T;
  displayOrder?: T;
  isVisible?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  countryCode?: T;
  website?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  description?: T;
  group?: T;
  isVisible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInARSEnabled?: T;
  priceInARS?: T;
  sku?: T;
  barcode?: T;
  oneOfAKind?: T;
  netContent?: T;
  netContentUnit?: T;
  salesUnit?: T;
  packedWeightGrams?: T;
  packageLengthMm?: T;
  packageWidthMm?: T;
  packageHeightMm?: T;
  lifecycleStatus?: T;
  image?: T;
  combinationKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  summary?: T;
  firstPublishedAt?: T;
  informationSections?:
    | T
    | {
        key?: T;
        title?: T;
        body?: T;
        isVisible?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  category?: T;
  additionalCategories?: T;
  brand?: T;
  taxonomyTags?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  countryOfOrigin?: T;
  region?: T;
  community?: T;
  originStory?: T;
  gallery?:
    | T
    | {
        image?: T;
        externalVideoUrl?: T;
        isPrimary?: T;
        caption?: T;
        id?: T;
      };
  lifecycleStatus?: T;
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInARSEnabled?: T;
  priceInARS?: T;
  sku?: T;
  barcode?: T;
  oneOfAKind?: T;
  netContent?: T;
  netContentUnit?: T;
  salesUnit?: T;
  packedWeightGrams?: T;
  packageLengthMm?: T;
  packageWidthMm?: T;
  packageHeightMm?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  acceptCurrentPrices?: T;
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        amount?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Optional logo override. Storefront falls back to wordmark.
   */
  logo?: (number | null) | Media;
  navItems?:
    | {
        link?: {
          type?: ('custom' | 'internal') | null;
          label?: string | null;
          /**
           * Absolute URL or site path (e.g. https://… or /shop).
           */
          url?: string | null;
          /**
           * Locale-free path (e.g. /shop, /about). Storefront prefixes locale.
           */
          path?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  cta?: {
    enabled?: boolean | null;
    link?: {
      type?: ('custom' | 'internal') | null;
      label?: string | null;
      /**
       * Absolute URL or site path (e.g. https://… or /shop).
       */
      url?: string | null;
      /**
       * Locale-free path (e.g. /shop, /about). Storefront prefixes locale.
       */
      path?: string | null;
      newTab?: boolean | null;
      appearance?: ('primary' | 'secondary') | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              link?: {
                type?: ('custom' | 'internal') | null;
                label?: string | null;
                /**
                 * Absolute URL or site path (e.g. https://… or /shop).
                 */
                url?: string | null;
                /**
                 * Locale-free path (e.g. /shop, /about). Storefront prefixes locale.
                 */
                path?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        link?: {
          type?: ('custom' | 'internal') | null;
          label?: string | null;
          /**
           * Absolute URL or site path (e.g. https://… or /shop).
           */
          url?: string | null;
          /**
           * Locale-free path (e.g. /shop, /about). Storefront prefixes locale.
           */
          path?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Optional override. Storefront can append the year.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  social?:
    | {
        platform: 'instagram' | 'facebook' | 'youtube' | 'x' | 'tiktok' | 'other';
        url: string;
        /**
         * Accessible label override.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Informational; storefront routing still owns active locale.
   */
  defaultLocale?: ('en' | 'es') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Fallback document title.
   */
  defaultTitle?: string | null;
  /**
   * Use %s for the page title segment.
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  /**
   * Without @ (e.g. pueblomagico).
   */
  twitterHandle?: string | null;
  robots?: {
    index?: boolean | null;
    follow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              url?: T;
              path?: T;
              newTab?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        link?:
          | T
          | {
              type?: T;
              label?: T;
              url?: T;
              path?: T;
              newTab?: T;
              appearance?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    url?: T;
                    path?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              url?: T;
              path?: T;
              newTab?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  contactEmail?: T;
  contactPhone?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  defaultLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultOgImage?: T;
  twitterHandle?: T;
  robots?:
    | T
    | {
        index?: T;
        follow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}