import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_categories_icon" AS ENUM('leaf', 'mountain', 'sun', 'ritual', 'heart');
  CREATE TYPE "public"."enum_variants_net_content_unit" AS ENUM('g', 'ml', 'unit');
  CREATE TYPE "public"."enum_variants_sales_unit" AS ENUM('unit', 'pack');
  CREATE TYPE "public"."enum_variants_lifecycle_status" AS ENUM('active', 'discontinued');
  CREATE TYPE "public"."enum__variants_v_version_net_content_unit" AS ENUM('g', 'ml', 'unit');
  CREATE TYPE "public"."enum__variants_v_version_sales_unit" AS ENUM('unit', 'pack');
  CREATE TYPE "public"."enum__variants_v_version_lifecycle_status" AS ENUM('active', 'discontinued');
  CREATE TYPE "public"."enum_products_lifecycle_status" AS ENUM('active', 'discontinued');
  CREATE TYPE "public"."enum_products_net_content_unit" AS ENUM('g', 'ml', 'unit');
  CREATE TYPE "public"."enum_products_sales_unit" AS ENUM('unit', 'pack');
  CREATE TYPE "public"."enum__products_v_version_lifecycle_status" AS ENUM('active', 'discontinued');
  CREATE TYPE "public"."enum__products_v_version_net_content_unit" AS ENUM('g', 'ml', 'unit');
  CREATE TYPE "public"."enum__products_v_version_sales_unit" AS ENUM('unit', 'pack');
  ALTER TABLE "categories" ALTER COLUMN "icon" DROP DEFAULT;
  ALTER TABLE "categories" ALTER COLUMN "icon" TYPE "enum_categories_icon" USING "icon"::"enum_categories_icon";
  ALTER TABLE "variants" ADD COLUMN "sku" varchar;
  ALTER TABLE "variants" ADD COLUMN "barcode" varchar;
  ALTER TABLE "variants" ADD COLUMN "one_of_a_kind" boolean DEFAULT false;
  ALTER TABLE "variants" ADD COLUMN "net_content" numeric;
  ALTER TABLE "variants" ADD COLUMN "net_content_unit" "enum_variants_net_content_unit";
  ALTER TABLE "variants" ADD COLUMN "sales_unit" "enum_variants_sales_unit" DEFAULT 'unit';
  ALTER TABLE "variants" ADD COLUMN "packed_weight_grams" numeric;
  ALTER TABLE "variants" ADD COLUMN "package_length_mm" numeric;
  ALTER TABLE "variants" ADD COLUMN "package_width_mm" numeric;
  ALTER TABLE "variants" ADD COLUMN "package_height_mm" numeric;
  ALTER TABLE "variants" ADD COLUMN "lifecycle_status" "enum_variants_lifecycle_status" DEFAULT 'active';
  ALTER TABLE "variants" ADD COLUMN "image_id" integer;
  ALTER TABLE "variants" ADD COLUMN "combination_key" varchar;
  ALTER TABLE "_variants_v" ADD COLUMN "version_sku" varchar;
  ALTER TABLE "_variants_v" ADD COLUMN "version_barcode" varchar;
  ALTER TABLE "_variants_v" ADD COLUMN "version_one_of_a_kind" boolean DEFAULT false;
  ALTER TABLE "_variants_v" ADD COLUMN "version_net_content" numeric;
  ALTER TABLE "_variants_v" ADD COLUMN "version_net_content_unit" "enum__variants_v_version_net_content_unit";
  ALTER TABLE "_variants_v" ADD COLUMN "version_sales_unit" "enum__variants_v_version_sales_unit" DEFAULT 'unit';
  ALTER TABLE "_variants_v" ADD COLUMN "version_packed_weight_grams" numeric;
  ALTER TABLE "_variants_v" ADD COLUMN "version_package_length_mm" numeric;
  ALTER TABLE "_variants_v" ADD COLUMN "version_package_width_mm" numeric;
  ALTER TABLE "_variants_v" ADD COLUMN "version_package_height_mm" numeric;
  ALTER TABLE "_variants_v" ADD COLUMN "version_lifecycle_status" "enum__variants_v_version_lifecycle_status" DEFAULT 'active';
  ALTER TABLE "_variants_v" ADD COLUMN "version_image_id" integer;
  ALTER TABLE "_variants_v" ADD COLUMN "version_combination_key" varchar;
  ALTER TABLE "products" ALTER COLUMN "lifecycle_status" DROP DEFAULT;
  ALTER TABLE "products" ALTER COLUMN "lifecycle_status" TYPE "enum_products_lifecycle_status" USING "lifecycle_status"::"enum_products_lifecycle_status";
  ALTER TABLE "products" ALTER COLUMN "lifecycle_status" SET DEFAULT 'active';
  ALTER TABLE "products" ADD COLUMN "sku" varchar;
  ALTER TABLE "products" ADD COLUMN "barcode" varchar;
  ALTER TABLE "products" ADD COLUMN "one_of_a_kind" boolean DEFAULT false;
  ALTER TABLE "products" ADD COLUMN "net_content" numeric;
  ALTER TABLE "products" ADD COLUMN "net_content_unit" "enum_products_net_content_unit";
  ALTER TABLE "products" ADD COLUMN "sales_unit" "enum_products_sales_unit" DEFAULT 'unit';
  ALTER TABLE "products" ADD COLUMN "packed_weight_grams" numeric;
  ALTER TABLE "products" ADD COLUMN "package_length_mm" numeric;
  ALTER TABLE "products" ADD COLUMN "package_width_mm" numeric;
  ALTER TABLE "products" ADD COLUMN "package_height_mm" numeric;
  ALTER TABLE "_products_v" ALTER COLUMN "version_lifecycle_status" DROP DEFAULT;
  ALTER TABLE "_products_v" ALTER COLUMN "version_lifecycle_status" TYPE "enum__products_v_version_lifecycle_status" USING "version_lifecycle_status"::"enum__products_v_version_lifecycle_status";
  ALTER TABLE "_products_v" ALTER COLUMN "version_lifecycle_status" SET DEFAULT 'active';
  ALTER TABLE "_products_v" ADD COLUMN "version_sku" varchar;
  ALTER TABLE "_products_v" ADD COLUMN "version_barcode" varchar;
  ALTER TABLE "_products_v" ADD COLUMN "version_one_of_a_kind" boolean DEFAULT false;
  ALTER TABLE "_products_v" ADD COLUMN "version_net_content" numeric;
  ALTER TABLE "_products_v" ADD COLUMN "version_net_content_unit" "enum__products_v_version_net_content_unit";
  ALTER TABLE "_products_v" ADD COLUMN "version_sales_unit" "enum__products_v_version_sales_unit" DEFAULT 'unit';
  ALTER TABLE "_products_v" ADD COLUMN "version_packed_weight_grams" numeric;
  ALTER TABLE "_products_v" ADD COLUMN "version_package_length_mm" numeric;
  ALTER TABLE "_products_v" ADD COLUMN "version_package_width_mm" numeric;
  ALTER TABLE "_products_v" ADD COLUMN "version_package_height_mm" numeric;
  ALTER TABLE "variants" ADD CONSTRAINT "variants_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_variants_v" ADD CONSTRAINT "_variants_v_version_image_id_media_id_fk" FOREIGN KEY ("version_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE UNIQUE INDEX "variants_sku_idx" ON "variants" USING btree ("sku");
  CREATE INDEX "variants_image_idx" ON "variants" USING btree ("image_id");
  CREATE UNIQUE INDEX "variants_combination_key_idx" ON "variants" USING btree ("combination_key");
  CREATE INDEX "_variants_v_version_version_sku_idx" ON "_variants_v" USING btree ("version_sku");
  CREATE INDEX "_variants_v_version_version_image_idx" ON "_variants_v" USING btree ("version_image_id");
  CREATE INDEX "_variants_v_version_version_combination_key_idx" ON "_variants_v" USING btree ("version_combination_key");
  CREATE UNIQUE INDEX "products_sku_idx" ON "products" USING btree ("sku");
  CREATE INDEX "_products_v_version_version_sku_idx" ON "_products_v" USING btree ("version_sku");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "variants" DROP CONSTRAINT "variants_image_id_media_id_fk";
  
  ALTER TABLE "_variants_v" DROP CONSTRAINT "_variants_v_version_image_id_media_id_fk";
  
  DROP INDEX "variants_sku_idx";
  DROP INDEX "variants_image_idx";
  DROP INDEX "variants_combination_key_idx";
  DROP INDEX "_variants_v_version_version_sku_idx";
  DROP INDEX "_variants_v_version_version_image_idx";
  DROP INDEX "_variants_v_version_version_combination_key_idx";
  DROP INDEX "products_sku_idx";
  DROP INDEX "_products_v_version_version_sku_idx";
  ALTER TABLE "categories" ALTER COLUMN "icon" DROP DEFAULT;
  ALTER TABLE "categories" ALTER COLUMN "icon" TYPE varchar USING "icon"::text;
  ALTER TABLE "variants" DROP COLUMN "sku";
  ALTER TABLE "variants" DROP COLUMN "barcode";
  ALTER TABLE "variants" DROP COLUMN "one_of_a_kind";
  ALTER TABLE "variants" DROP COLUMN "net_content";
  ALTER TABLE "variants" DROP COLUMN "net_content_unit";
  ALTER TABLE "variants" DROP COLUMN "sales_unit";
  ALTER TABLE "variants" DROP COLUMN "packed_weight_grams";
  ALTER TABLE "variants" DROP COLUMN "package_length_mm";
  ALTER TABLE "variants" DROP COLUMN "package_width_mm";
  ALTER TABLE "variants" DROP COLUMN "package_height_mm";
  ALTER TABLE "variants" DROP COLUMN "lifecycle_status";
  ALTER TABLE "variants" DROP COLUMN "image_id";
  ALTER TABLE "variants" DROP COLUMN "combination_key";
  ALTER TABLE "_variants_v" DROP COLUMN "version_sku";
  ALTER TABLE "_variants_v" DROP COLUMN "version_barcode";
  ALTER TABLE "_variants_v" DROP COLUMN "version_one_of_a_kind";
  ALTER TABLE "_variants_v" DROP COLUMN "version_net_content";
  ALTER TABLE "_variants_v" DROP COLUMN "version_net_content_unit";
  ALTER TABLE "_variants_v" DROP COLUMN "version_sales_unit";
  ALTER TABLE "_variants_v" DROP COLUMN "version_packed_weight_grams";
  ALTER TABLE "_variants_v" DROP COLUMN "version_package_length_mm";
  ALTER TABLE "_variants_v" DROP COLUMN "version_package_width_mm";
  ALTER TABLE "_variants_v" DROP COLUMN "version_package_height_mm";
  ALTER TABLE "_variants_v" DROP COLUMN "version_lifecycle_status";
  ALTER TABLE "_variants_v" DROP COLUMN "version_image_id";
  ALTER TABLE "_variants_v" DROP COLUMN "version_combination_key";
  ALTER TABLE "products" ALTER COLUMN "lifecycle_status" DROP DEFAULT;
  ALTER TABLE "products" ALTER COLUMN "lifecycle_status" TYPE varchar USING "lifecycle_status"::text;
  ALTER TABLE "products" ALTER COLUMN "lifecycle_status" SET DEFAULT 'active';
  ALTER TABLE "products" DROP COLUMN "sku";
  ALTER TABLE "products" DROP COLUMN "barcode";
  ALTER TABLE "products" DROP COLUMN "one_of_a_kind";
  ALTER TABLE "products" DROP COLUMN "net_content";
  ALTER TABLE "products" DROP COLUMN "net_content_unit";
  ALTER TABLE "products" DROP COLUMN "sales_unit";
  ALTER TABLE "products" DROP COLUMN "packed_weight_grams";
  ALTER TABLE "products" DROP COLUMN "package_length_mm";
  ALTER TABLE "products" DROP COLUMN "package_width_mm";
  ALTER TABLE "products" DROP COLUMN "package_height_mm";
  ALTER TABLE "_products_v" ALTER COLUMN "version_lifecycle_status" DROP DEFAULT;
  ALTER TABLE "_products_v" ALTER COLUMN "version_lifecycle_status" TYPE varchar USING "version_lifecycle_status"::text;
  ALTER TABLE "_products_v" ALTER COLUMN "version_lifecycle_status" SET DEFAULT 'active';
  ALTER TABLE "_products_v" DROP COLUMN "version_sku";
  ALTER TABLE "_products_v" DROP COLUMN "version_barcode";
  ALTER TABLE "_products_v" DROP COLUMN "version_one_of_a_kind";
  ALTER TABLE "_products_v" DROP COLUMN "version_net_content";
  ALTER TABLE "_products_v" DROP COLUMN "version_net_content_unit";
  ALTER TABLE "_products_v" DROP COLUMN "version_sales_unit";
  ALTER TABLE "_products_v" DROP COLUMN "version_packed_weight_grams";
  ALTER TABLE "_products_v" DROP COLUMN "version_package_length_mm";
  ALTER TABLE "_products_v" DROP COLUMN "version_package_width_mm";
  ALTER TABLE "_products_v" DROP COLUMN "version_package_height_mm";
  DROP TYPE "public"."enum_categories_icon";
  DROP TYPE "public"."enum_variants_net_content_unit";
  DROP TYPE "public"."enum_variants_sales_unit";
  DROP TYPE "public"."enum_variants_lifecycle_status";
  DROP TYPE "public"."enum__variants_v_version_net_content_unit";
  DROP TYPE "public"."enum__variants_v_version_sales_unit";
  DROP TYPE "public"."enum__variants_v_version_lifecycle_status";
  DROP TYPE "public"."enum_products_lifecycle_status";
  DROP TYPE "public"."enum_products_net_content_unit";
  DROP TYPE "public"."enum_products_sales_unit";
  DROP TYPE "public"."enum__products_v_version_lifecycle_status";
  DROP TYPE "public"."enum__products_v_version_net_content_unit";
  DROP TYPE "public"."enum__products_v_version_sales_unit";`)
}
